output_subdir: null
experiment:
  seed: 3
  run_id: Luisas-MacBook-Air.local-20251124T193034-8860
  num_simulations: 1
  save_root_dir: apresentacao/simulacoes/
  if_save_config: true
  if_save_p_net: false
  if_save_v_nets: false
  if_load_p_net: false
  if_load_v_nets: false
  save_run_id_dir: apresentacao/simulacoes/ga_meta/Luisas-MacBook-Air.local-20251124T193034-8860
system:
  renew_v_net_simulator: false
  if_offline_system: false
  if_changeable_v_nets: false
  if_time_window: false
  time_window_size: 100
solver:
  solver_name: ga_meta
  matching_mathod: greedy
  shortest_method: k_shortest
  reusable: false
  node_ranking_method: order
  link_ranking_method: order
  k_shortest: 20
  allow_revocable: false
  allow_rejection: false
  sub_solver_name: null
  pretrained_model_path: ''
  pretrained_subsolver_model_path: ''
recorder:
  record_dir_name: records
  if_save_records: true
  if_temp_save_records: true
  summary_file_name: summary.csv
logger:
  log_dir_name: logs
  project_name: virne
  experiment_name: ga_tree_experiment
  level: INFO
  verbose: 1
  backends:
  - console
  - file
  - tensorboard
  log_show_interval: 20
  log_file_name: running.log
training:
  seed: null
  use_cuda: true
  gpu_id: 0
  distributed_training: false
  num_train_epochs: 50
  num_workers: 10
  batch_size: 128
  log_interval: 1
  save_interval: 10
  eval_interval: 10
  learning_rate: 0.001
  model_dir_name: models
  weight_decay: 1.0e-05
  if_use_random_training_seed: true
inference:
  decode_strategy: greedy
  k_searching: 1
nn:
  embedding_dim: 128
  hidden_dim: 128
  num_layers: 1
  num_gnn_layers: 3
  dropout_prob: 0.0
  batch_norm: false
rl:
  gamma: 0.99
  target_steps: 256
  if_use_negative_sample: true
  if_use_baseline_solver: false
  if_allow_baseline_unsafe_solve: false
  reward_calculator:
    name: fixed_intermediate
    intermediate_reward: 0.1
  feature_constructor:
    name: p_net_v_node
    extracted_attr_types:
    - resource
    if_use_node_status_flags: true
    if_use_aggregated_link_attrs: true
    if_use_degree_metric: true
    if_use_more_topological_metrics: true
    num_extracted_p_node_attrs: 1
    num_extracted_p_link_attrs: 1
    num_extracted_v_node_attrs: 1
    num_extracted_v_link_attrs: 1
    p_num_nodes: 32
  learning_rate:
    actor: 0.001
    critic: 0.001
    encoder: 0.001
    cost_critic: 0.001
    lambda_net: 0.001
    penalty_params: 0.0001
  coef_critic_loss: 0.5
  coef_entropy_loss: 0.01
  coef_mask_loss: 0.01
  l2reg_rate: 0.00025
  mask_actions: true
  maskable_policy: true
  clip_grad: true
  max_grad_norm: 0.5
  norm_critic_loss: false
  weight_decay: 1.0e-05
  norm_reward: false
  norm_advantage: true
  eps_clip: 0.2
  target_kl: null
  gae_lambda: 0.98
  repeat_times: 10
  explore_rate: 0.9
  safe_rl:
    srl_cost_budget: 0.2
    srl_alpha: 1.0
    srl_beta: 0.1
v_sim_setting:
  num_v_nets: 200
  topology:
    type: random
    random_prob: 0.5
  v_net_size:
    distribution: uniform
    dtype: int
    low: 2
    high: 10
  arrival_rate:
    distribution: poisson
    dtype: float
    lam: 0.04
    reciprocal: true
  lifetime:
    distribution: exponential
    dtype: float
    scale: 500
  node_attrs_setting:
  - name: cpu
    type: resource
    owner: node
    distribution: uniform
    dtype: int
    generative: true
    low: 0
    high: 20
  link_attrs_setting:
  - name: bw
    type: resource
    owner: link
    distribution: uniform
    dtype: int
    generative: true
    low: 0
    high: 50
  graph_attrs_setting: null
  output:
    save_dir: dataset/v_nets
    v_nets_save_dir: v_nets
    v_nets_file_name: v_net.gml
    events_file_name: events.yaml
    setting_file_name: v_sim_setting.yaml
p_net_setting:
  topology:
    num_nodes: 63
    type: tree
    branching_factor: 2
    wm_alpha: 0.5
    wm_beta: 0.2
  node_attrs_setting:
  - name: cpu
    type: resource
    owner: node
    distribution: uniform
    dtype: int
    generative: true
    high: 100
    low: 50
  - name: max_cpu
    type: extrema
    owner: node
    originator: cpu
  link_attrs_setting:
  - name: bw
    type: resource
    owner: link
    distribution: uniform
    dtype: int
    generative: true
    high: 100
    low: 50
  - name: max_bw
    type: extrema
    owner: link
    originator: bw
  output:
    save_dir: dataset/p_net
    file_name: tree_p_net.gml
simulation:
  p_net_dataset_dir: dataset/p_net/32-tree_[0.5-0.2]-cpu_[50-100]-max_cpu_None-bw_[50-100]-max_bw_None-seed_3
  v_nets_dataset_dir: dataset/v_nets/200-[2-10]-random-500-0.04-cpu_[0-20]-bw_[0-50]-seed_3
  p_net_setting_num_nodes: 32
  p_net_setting_num_node_attrs: 2
  p_net_setting_num_link_attrs: 2
  p_net_setting_num_node_resource_attrs: 1
  p_net_setting_num_link_resource_attrs: 1
  p_net_setting_num_node_extrema_attrs: 1
  p_net_setting_num_link_extrema_attrs: 1
  v_sim_setting_num_node_attrs: 1
  v_sim_setting_num_link_attrs: 1
  v_sim_setting_num_node_resource_attrs: 1
  v_sim_setting_num_link_resource_attrs: 1
  v_sim_setting_num_node_non_status_attrs: 1
  v_sim_setting_num_link_non_status_attrs: 1
  p_net_num_nodes: 63
