training:
  seed: null
  use_cuda: true
  cuda_id: 0
  distributed_training: false
  num_train_epochs: 100
  num_workers: 10
  batch_size: 128
  save_interval: 10
  eval_interval: 10

nn:
  embedding_dim: 128
  hidden_dim: 128
  num_layers: 1
  num_gnn_layers: 5
  dropout_prob: 0.0
  batch_norm: false

rl:
  rl_gamma: 0.99
  target_steps: 256
  explore_rate: 0.9
  gae_lambda: 0.98
  repeat_times: 10
  lr_actor: 0.001
  lr_critic: 0.001
  decode_strategy: greedy
  k_searching: 1
  # losses
  coef_critic_loss: 0.5
  coef_entropy_loss: 0.01
  coef_mask_loss: 0.01
  reward_weight: 0.1
  lr_penalty_params: 0.001
  lr_cost_critic: 0.001
  l2reg_rate: 0.00025
  # tricks
  mask_actions: true
  maskable_policy: true
  use_negative_sample: true
  norm_advantage: true
  clip_grad: true
  eps_clip: 0.2
  max_grad_norm: 0.5
  norm_critic_loss: false
  use_baseline_solver: false
  weight_decay: 0.00001

  safe_rl:
    srl_cost_budget: 0.2
    srl_alpha: 1.0
    srl_beta: 0.1

